version: '3.1'

services:
  db1:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      # (this is just an example, not intended to be a production configuration)
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      # (this is just an example, not intended to be a production configuration)
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql